# Generated by Django 5.1.1 on 2024-10-26 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0002_wishlist_car_wishlist_created_at_alter_wishlist_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='created_at',
        ),
    ]
